const ayarlar = {
  TOKEN: "MTA2NjY5MDI4NjIyMDIzMDcyNw.GJlUIz.MdtYZtIA1afWZorO43eOGCUrm8murPM0Q-YkOc", // ASSAGIYI OKU
  sahip: "851774307466084383",
  prefix: "e!"
};

module.exports = ayarlar;

//BOT TOKENINIZI EGER BOT GLITCHDE KALACAK
//ISE .ENV DOSYASINA
//EGER VDS YE KURACAK ISENIZ YUKARIYA 1. SATIRA YAZIN